import { Component, OnInit } from '@angular/core';
import {CdkDragDrop, moveItemInArray, transferArrayItem} from '@angular/cdk/drag-drop';




@Component({
  selector: 'app-coursescheduler',
  templateUrl: './coursescheduler.component.html',
  styleUrls: ['./coursescheduler.component.css']
})
export class CourseschedulerComponent implements OnInit {

  update_in_progress = false;

  course_years = [ '2019', '2020', '2021', '2022', '2023', '2024', '2025', '2026', '2027', '2028'];

  course_semesters = [ 'Spring', 'Summer', 'Fall', 'Winter'];

  course_yr = '2019';

  course_sem = 'Fall';

  course_yr_prev = this.course_yr;

  course_sem_prev = this.course_sem;

  day_hourly = [
    {'day': '0',
      '800': [
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''}
      ],
      '900': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1000': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1100': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1200': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1300': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1400': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1500': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1600': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1700': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ]
    },
    {'day': '1',
      '800': [
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''}
      ],
      '900': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1000': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1100': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1200': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1300': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1400': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1500': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1600': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1700': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ]
    },
    {'day': '2',
      '800': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
    ],
    '900': [
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''}
      ],
    '1000': [
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''}
      ],
    '1100': [
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''}
      ],
    '1200': [
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''}
      ],
    '1300': [
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''}
      ],
    '1400': [
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''}
      ],
    '1500': [
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''}
      ],
    '1600': [
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''}
      ],
    '1700': [
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''},
      {'prof_name': '',
       'course_name': '',
       'course': '',
       'prof_id': '',
       'course_id': ''}
      ]
    },
    {'day': '3',
      '800': [
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''}
      ],
      '900': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1000': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1100': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1200': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1300': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1400': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1500': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1600': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1700': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ]
    },
    {'day': '4',
      '800': [
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''}
          
      ],
      '900': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1000': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1100': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1200': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1300': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1400': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1500': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1600': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1700': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ]
    },
    {'day': '5',
      '800': [
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''}
      ],
      '900': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1000': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1100': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1200': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1300': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1400': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1500': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1600': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1700': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ]
    },
    {'day': '6',
      '800': [
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''},
          {'prof_name': '',
           'course_name': '',
           'course': '',
           'prof_id': '',
           'course_id': ''}
      ],
      '900': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1000': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1100': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1200': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1300': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1400': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1500': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1600': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ],
      '1700': [
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''},
        {'prof_name': '',
         'course_name': '',
         'course': '',
         'prof_id': '',
         'course_id': ''}
        ]
    },
    {'course_year': '2019', 'course_semester': 'Fall'}
  ];

  courses_choice = {
      'prof_name': 'Thomas',
      'prof_id': 'Thomas',
      'courses': [
        {'course_name': 'CS101', 'course': 'CS101', 'course_id': 'CS101'},
        {'course_name': 'CS102', 'course': 'CS102', 'course_id': 'CS102'},
        {'course_name': 'CS103', 'course': 'CS103', 'course_id': 'CS103'},
        {'course_name': 'CS104', 'course': 'CS104', 'course_id': 'CS104'}
      ]
    };

  courses_offer = [
    { 'prof_name': 'Choose One', 'prof_id': '', 'courses': [] },
    { 'prof_name': 'Rosso', 'prof_id': '1',
      'courses': [
        { 'course_name': 'CS 201', 'course': '201', 'course_id': '1' },
        { 'course_name': 'CS 202', 'course': '202', 'course_id': '2' },
        { 'course_name': 'CS 203', 'course': '203', 'course_id': '3' }]},
    { 'prof_name': 'Lee', 'prof_id': '2',
      'courses': [
        { 'course_name': 'CS 204', 'course': '204', 'course_id': '4' },
        { 'course_name': 'CS 205', 'course': '205', 'course_id': '5' },
        { 'course_name': 'CS 206', 'course': '206', 'course_id': '6' }]},
    { 'prof_name': 'Matthew', 'prof_id': '3',
      'courses': [
        { 'course_name': 'CS 207', 'course': '207', 'course_id': '7' },
        { 'course_name': 'CS 208', 'course': '208', 'course_id': '8' },
        { 'course_name': 'CS 209', 'course': '209', 'course_id': '9' }]}
  ];

  
   
  constructor() {}


  ngOnInit() {
    
  }

 

  drop_to_coursechoice(event: CdkDragDrop<string[]>) {
    console.log('drop to course choice');
  }

  drop_to_trash(event: CdkDragDrop<string[]>) {
    console.log('drop to trash');
    if (event.previousContainer.id === 'course_choice') { return; }
    try {
      let objDrop = event.previousContainer.data;
      let objCur  = event.container.data;
      let objCls: any = [];
      let hlen =  event.container.id.length ;
      let hourly = event.container.id.substr(0, (hlen - 1));
      let daily = event.container.id.substr((hlen - 1), 1);
      hlen = event.previousContainer.id.length;
      let hourly_prev = event.previousContainer.id.substr(0, (hlen - 1));
      let daily_prev = event.previousContainer.id.substr((hlen - 1), 1);

      objCls = objDrop[daily_prev][hourly_prev];
      objCls[event.previousIndex]['prof_name'] = '';
      objCls[event.previousIndex]['course_name'] = '';
      objCls[event.previousIndex]['course'] = '';
      objCls[event.previousIndex]['prof_id'] = '';
      objCls[event.previousIndex]['course_id'] = '0';
    } catch (e) {
      console.log(e.console.error());
    }

  }

  drop(event: CdkDragDrop<string[]>) {
    console.log(event.container.data);
    console.log(event.previousContainer.data)
    if (event.previousContainer === event.container) {
      moveItemInArray(event.container.data, event.previousIndex, event.currentIndex);
      return;
    }
    try {
      let objDrop = event.previousContainer.data;
      let objCur  = event.container.data;
      let objCls: any = [];
      let hlen =  event.container.id.length ;
      let hourly = event.container.id.substr(0, (hlen - 1));
      let daily = event.container.id.substr((hlen - 1), 1);
      console.log(daily, hourly, objCur[daily][hourly]);
      console.log(objDrop['courses'][event.previousIndex]);

      objCls = objDrop['courses'][event.previousIndex];
      for ( const cur_entry of objCur[daily][hourly] ) {
        if ( cur_entry['prof_name'] === '' ) {
          cur_entry['prof_name'] = objDrop['prof_name'];
          cur_entry['prof_id'] = objDrop['prof_id'];
          cur_entry['course_name'] = objCls['course_name'];
          cur_entry['course'] = objCls['course'];
          cur_entry['course_id'] = objCls['course_id'];
          break;
        }
      }
      return;
    } catch (e) {
      console.log('not from course_choice');
    }
    
    try {
      let objDrop = event.previousContainer.data;
      let objCur  = event.container.data;
      let objCls: any = [];
      let hlen =  event.container.id.length ;
      let hourly = event.container.id.substr(0, (hlen - 1));
      let daily = event.container.id.substr((hlen - 1), 1);
      hlen = event.previousContainer.id.length;
      let hourly_prev = event.previousContainer.id.substr(0, (hlen - 1));
      let daily_prev = event.previousContainer.id.substr((hlen - 1), 1);
      console.log('cur', daily_prev, hourly_prev, objCur[daily][hourly]);
      console.log('prev',daily_prev, hourly_prev, objCur[daily_prev][hourly_prev]);

      objCls = objDrop[daily_prev][hourly_prev];
      for ( const cur_entry of objCur[daily][hourly] ) {
        if ( cur_entry['prof_name'] === '' ) {
          cur_entry['prof_name'] = objCls[event.previousIndex]['prof_name'];
          cur_entry['course_name'] = objCls[event.previousIndex]['course_name'];
          cur_entry['course'] = objCls[event.previousIndex]['course'];
          cur_entry['prof_id'] = objCls[event.previousIndex]['prof_id'];
          cur_entry['course_id'] = objCls[event.previousIndex]['course_id'];
          objCls[event.previousIndex]['prof_name'] = '';
          objCls[event.previousIndex]['course_name'] = '';
          objCls[event.previousIndex]['course'] = '';
          objCls[event.previousIndex]['prof_id'] = '';
          objCls[event.previousIndex]['course_id'] = '';
          break;
        }
      }
    } catch (e) {
      console.log(e.console.error());
    }

  }

  
  clickMe(){
    // this.done.forEach( function (value) {
    //  console.log(value);
    // });
  }

  day_hourly_dbclick(day, hourly, i) {
    console.log(day, hourly, i);
  }

  onSelectCourseYear(kourse_yr) {
    console.log('yr selected: ', this.course_yr, ' prev: ', this.course_yr_prev);
    this.course_yr_prev = this.course_yr;
   

  }

  onSelectCourseSemester(kourse_sem) {
    console.log('sem selected: ', this.course_sem, ' prev: ', this.course_sem_prev);
   

    this.course_sem_prev = this.course_sem;
  }

  
}
